name: Build Example Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Check Directory
        run: pwd
      - name: Check Test File
        run: cat ./test/test_launch_data_reader/test.csv
      - name: Build Example Test
        run: pio run --environment teensy41 
